h5p/moodle-mod_hvp

README.md
To make it more clear to those who are not familiar with inter-project code and library dependencies.
"Copy the entire https://github.com/h5p/h5p-php-library code into /moodle/mod/hvp/library"
=> Add more info about the install process

classes/framework.php
Removed LIMIT in a query (https://github.com/h5p/h5p-moodle-plugin/issues/38#issuecomment-187646660)
=> Error #38 Error Oracle

.travis.yml, ajax.php, autoloader.php, backup/moodle2/backup_hvp_activity_task.class.php, backup/moodle2/backup_hvp_settingslib.php, backup/moodle2/backup_hvp_stepslib.php, backup/moodle2/restore_hvp_activity_task.class.php, backup/moodle2/restore_hvp_stepslib.php, classes/content_user_data.php, classes/file_storage.php, classes/framework.php, classes/results.php, classes/upload_libraries_form.php, classes/user_grades.php, dataviews.js, db/upgrade.php, grade.php, index.php, lang/en/hvp.php, lib.php, library_list.php, locallib.php, mod_form.php, settings.php, upgrade_content_page.php, view.php
Okay. Fixed the ones I could see that were fixed incorrectly.
For reference, pre-fixes: https://travis-ci.org/POETGroup/moodle-mod_hvp/builds/120120889
After fixes: https://travis-ci.org/POETGroup/moodle-mod_hvp/builds/120127893
=> Poet 0.x - Moodle coding guideline fixes (take 2)

lang/de/hvp.php
I had this request opened before (#52), but as pointed out by @juho-jaakkola with bad commit messages and three commits for one task, here is the prettier version. Thanks for helping!
=> Adding german translation

classes/content_user_data.php, lang/en/hvp.php
Changed to valid return state when loading user data.
Added error message when missing parameters.
Fixes #31
=> Fixed json parseerror on getting user data.

ajax.php, classes/content_user_data.php, classes/framework.php, classes/results.php, classes/user_grades.php, db/access.php, lang/en/hvp.php, version.php
Added capabilities for:
- delete content user data
- save content user data
- update libraries
- restrict libraries
- view results
- save results
=> Check permission handling.

classes/framework.php
=> Fix cron task

classes/user_grades.php, db/access.php, lang/en/hvp.php, lib.php, version.php
Fixed some capabilities.
Fixes #28
=> Added permission checks for getting content files.

db/install.xml, db/upgrade.php, lib.php, mod_form.php, version.php, view.php
Should fix h5p/h5p-moodle-plugin#46
=> New Feature: Add support for module Intro (above H5P content)

classes/editor_framework.php, version.php
Changes in https://github.com/h5p/h5p-editor-php-library/commit/2f45a90b1fc931c5253bc190b97dbab461f9580b should also be checked
=> Provided context for restricted libraries capability. #28

db/install.php, lang/en/hvp.php
Added welcome message when installing H5P with links to relevant information for new users.
=> Welcome message

lang/de/hvp.php
Updated the german translation to take care of the latest changes
=> Update german translation

db/install.php, lang/en/hvp.php
Changed install text to reflect that libraries has been installed
=> Install text fix

classes/framework.php, locallib.php, view.php
=> Changed sessioncookiepath to httpswwwroot.

lang/he/hvp.php
Let's start with something ;-) 
At least from the learner's perspective
=> Initial Hebrew translation

lang/de/hvp.php
I fixed some typos in the German language file and added the string for "hvp:updatesavailable" that seemed to be missing so far.
=> small fixes of German language

lang/fr/hvp.php
Hi,
Just translated the lang/en/hvp.php file into a new file lang/fr/hvp.php
=> add fr lang file

classes/framework.php, version.php
Fix for https://github.com/h5p/h5p-moodle-plugin/issues/101 and https://github.com/h5p/h5p-moodle-plugin/issues/102
=> Upload libraries

lang/ca/hvp.php
I have translated the H5P Moodle module messages into Catalan. Thanks for merging them!
=> Added Catalan translation

lang/hvp.php
=> bs-hvp.php

db/install.xml
this file is generated by the standard Moodle xmldb tool - I have simply loaded the file and re-saved using the valid format.
=> Fix #216 fix install.xml structure using moodle xmldb tool.

mod_form.php
If not, clean up the data manually.
=> Fix issue#242 check if moodleform_mod class has a get_data method

lang/fr/hvp.php
=> Update french translations

pix/icon.svg
This PR covers issue #254
Re-targeted to master branch.
=> Issue 254: Resize icon.svg down to 24x24.

embed.php
=> Issue #344: Release session lock before embed

lib.php
see my post in H5P forums at https://h5p.org/node/121088
=> Implementation of core_calendar notifications

classes/privacy/provider.php
this hasn't been tested very well, but might work - we'll do some internal testing on this too and let you know if we have any issues.
This should fix failing unit tests on Moodle 3.7
=> Fix #236 add userlist privacy classes.

LICENSE
Fixes: https://github.com/h5p/moodle-mod_hvp/issues/485
=> Fix LICENSE inconsistency - changing to gpl v3 to match code

view.php
=> Omit double headings (and intro) on Moodle ≥ 4.0.0 fixes #450.

index.php
The index page doesn't sanitize the activity name upon retrieval from the database, allowing for potential XSS to take place
Resolves: #500
=> Fixed potential XSS issue

classes/view_assets.php, grade.php, lang/en/hvp.php, review.php, share.php
=> Added error message definitions to lang strings file

classes/file_storage.php
=> Check max upload file size and use antivirus if apply

locallib.php, mod_form.php, styles.css
I updated the code to comply with Moodle 4.3 as follows:
- added suffix to completion rules in mod_form.php
- imported h5p css files into styles.css and removed require CSS from locallib.php
This will fix #521.
=> Updates for Moodle 4.3+
